export type Tier = "Free" | "Freemium" | "Paid"

export interface ResourceItem {
  id: string
  title: string
  description: string
  tier: Tier
  href: string
  tags: string[]
}

export interface ResourceCategory {
  slug: string
  name: string
  description: string
  icon: string        // lucide icon name for dynamic rendering
  accent: string      // tailwind text colour class
  resources: ResourceItem[]
}

// ─── Helpers ────────────────────────────────────────────────────────────────
function r(
  id: string, title: string, description: string,
  tier: Tier, href: string, tags: string[]
): ResourceItem { return { id, title, description, tier, href, tags } }

// ─── Category Data ───────────────────────────────────────────────────────────
export const RESOURCE_CATEGORIES: ResourceCategory[] = [
  {
    slug: "geo-ai-search",
    name: "GEO & AI Search",
    description: "Optimize your content for AI-generated search results across ChatGPT, Perplexity, Claude, Gemini, and Google AI Overviews.",
    icon: "Globe",
    accent: "text-primary",
    resources: [
      r("geo-1",  "GEO Optimization Complete Guide",        "End-to-end playbook for ranking in AI-generated answers across all major LLMs",                                   "Free",     "https://searchengineland.com/geo-guide",                 ["geo", "seo", "ai-search"]),
      r("geo-2",  "Google AI Overviews Best Practices",     "Official Google guidance on optimizing content for AI Overview inclusion",                                        "Free",     "https://developers.google.com/search/docs/appearance/ai-overviews", ["google", "ai-overviews", "seo"]),
      r("geo-3",  "Perplexity SEO Visibility Checklist",    "25-point checklist for getting cited in Perplexity answers",                                                     "Free",     "#",                                                       ["perplexity", "seo", "checklist"]),
      r("geo-4",  "ChatGPT Search Optimization Guide",      "How ChatGPT Browse selects and cites pages — and how to get included",                                           "Free",     "#",                                                       ["chatgpt", "search", "citations"]),
      r("geo-5",  "LLM Citation Patterns: 2026 Analysis",   "Research report analyzing what content gets cited across 6 major LLMs",                                          "Free",     "#",                                                       ["research", "citations", "llm"]),
      r("geo-6",  "Schema Markup for AI Visibility",        "Structured data types that improve AI Overview inclusion rate by up to 40%",                                     "Free",     "#",                                                       ["schema", "structured-data", "seo"]),
      r("geo-7",  "Entity-Based SEO for the AI Era",        "How to build topical authority and entity signals LLMs recognise",                                               "Free",     "#",                                                       ["entity", "authority", "seo"]),
      r("geo-8",  "FAQ Content That Gets Cited",             "Formatting and length guidelines that maximise FAQ citation probability",                                        "Free",     "#",                                                       ["faq", "content", "structure"]),
      r("geo-9",  "GEO Score Benchmarks by Industry",       "Median GEO scores across 12 verticals — see where you stand",                                                    "Free",     "#",                                                       ["benchmarks", "geo-score"]),
      r("geo-10", "Multi-LLM Visibility Tracker Template",  "Google Sheets template for tracking your brand mentions across 5 LLMs weekly",                                   "Free",     "#",                                                       ["template", "tracking"]),
      r("geo-11", "AI Overview Trigger Analysis Tool",      "Free Chrome extension that flags which queries trigger AI Overviews in your niche",                              "Free",     "#",                                                       ["tool", "chrome-extension", "ai-overviews"]),
      r("geo-12", "GEO for E-commerce Guide",               "Product page and category optimisation strategies specific to AI shopping queries",                              "Free",     "#",                                                       ["ecommerce", "product-pages"]),
      r("geo-13", "Local Business GEO Playbook",            "Hyperlocal AI search strategies for brick-and-mortar and service businesses",                                    "Free",     "#",                                                       ["local", "small-business"]),
      r("geo-14", "Competitor GEO Gap Analysis Framework",  "Step-by-step framework to find AI citation gaps your competitors are exploiting",                                "Freemium", "#",                                                       ["competitive", "analysis"]),
      r("geo-15", "GEO Monthly Report Template",            "Client-ready PDF/Notion report template for monthly GEO visibility reporting",                                   "Freemium", "#",                                                       ["template", "reporting", "agency"]),
      r("geo-16", "Advanced GEO Keyword Research",          "Finding queries where AI Overviews are present and you can win citations",                                       "Freemium", "#",                                                       ["keyword-research", "advanced"]),
      r("geo-17", "AI Answer Engine Comparison",            "Deep comparison of how ChatGPT Search, Perplexity, and Claude handle sources",                                   "Free",     "#",                                                       ["comparison", "research"]),
      r("geo-18", "GEO for SaaS Landing Pages",             "Conversion-optimised GEO strategies for software product pages",                                                 "Free",     "#",                                                       ["saas", "landing-pages"]),
      r("geo-19", "Voice Search & AI Assistant Optimisation","Future-proofing content for Alexa, Siri, and AI assistant ecosystems",                                          "Free",     "#",                                                       ["voice-search", "assistants"]),
      r("geo-20", "Content Freshness for AI Visibility",    "How update frequency and date signals affect LLM citation selection",                                            "Free",     "#",                                                       ["freshness", "content"]),
      r("geo-21", "GEO Agency Service Package Template",    "Proposal and deliverables template for selling GEO services to clients",                                         "Paid",     "#",                                                       ["agency", "proposals", "template"]),
      r("geo-22", "Programmatic GEO Content Playbook",      "Scaling GEO-optimised pages with programmatic content — without penalties",                                      "Paid",     "#",                                                       ["programmatic", "scale"]),
      r("geo-23", "GEO for B2B SaaS",                       "Account-based content strategies optimised for B2B AI search discovery",                                        "Free",     "#",                                                       ["b2b", "saas"]),
      r("geo-24", "GEO Technical Audit Checklist",          "50-point technical audit covering schema, speed, structure, and entity clarity",                                 "Free",     "#",                                                       ["audit", "technical"]),
    ],
  },
  {
    slug: "agentic-ai",
    name: "Agentic AI",
    description: "Guides, patterns, and tools for building, deploying, and auditing production-grade AI agent systems.",
    icon: "Bot",
    accent: "text-sky-400",
    resources: [
      r("ag-1",  "Agent Architecture Patterns",             "Common patterns for production agentic systems: ReAct, Plan-and-Execute, MRKL",                                  "Free",     "#",                                                       ["architecture", "patterns"]),
      r("ag-2",  "OpenClaw Getting Started Guide",          "Build your first audited agent skill with OpenClaw in under 30 minutes",                                         "Free",     "#",                                                       ["openclaw", "getting-started"]),
      r("ag-3",  "Multi-Agent Orchestration Deep Dive",     "Coordinate agents across pipelines with durable state and human-in-the-loop",                                    "Free",     "#",                                                       ["orchestration", "multi-agent"]),
      r("ag-4",  "LangChain vs LangGraph vs AutoGen",       "Technical comparison of the three dominant agentic frameworks in 2026",                                          "Free",     "#",                                                       ["langchain", "langgraph", "comparison"]),
      r("ag-5",  "Agent Memory Systems Explained",          "Short-term, long-term, episodic, and semantic memory for AI agents",                                             "Free",     "#",                                                       ["memory", "rag"]),
      r("ag-6",  "Tool Use and Function Calling Guide",     "How to design reliable tool schemas for ChatGPT, Claude, and Gemini",                                            "Free",     "#",                                                       ["tool-use", "function-calling"]),
      r("ag-7",  "Agent Reliability Patterns",              "Retry logic, fallbacks, circuit breakers, and error recovery for production agents",                             "Free",     "#",                                                       ["reliability", "production"]),
      r("ag-8",  "Durable Agent Workflows with Vercel",     "Building resumable, fault-tolerant agent workflows using Vercel Workflow SDK",                                   "Free",     "https://useworkflow.dev",                                ["vercel", "workflows", "durable"]),
      r("ag-9",  "Agent Evaluation Framework",              "How to measure agent accuracy, tool usage efficiency, and task completion rate",                                  "Free",     "#",                                                       ["eval", "testing"]),
      r("ag-10", "Structured Output Extraction Patterns",   "Reliable JSON and schema extraction from LLM outputs using Zod and AI SDK",                                      "Free",     "#",                                                       ["structured-output", "zod"]),
      r("ag-11", "Human-in-the-Loop Agent Design",          "When and how to interrupt agent execution for human review",                                                      "Free",     "#",                                                       ["hitl", "safety"]),
      r("ag-12", "Agent Security: Prompt Injection",        "Defending against prompt injection in LLM-powered agent systems",                                                 "Free",     "#",                                                       ["security", "prompt-injection"]),
      r("ag-13", "Computer-Use Agents: State of Play",      "Overview of computer-use agents, benchmarks, and production readiness in 2026",                                  "Free",     "#",                                                       ["computer-use", "claude"]),
      r("ag-14", "Agent Observability with LangSmith",      "Tracing, debugging, and monitoring production agent runs",                                                        "Free",     "#",                                                       ["observability", "monitoring"]),
      r("ag-15", "Agentic RAG Architecture",                "Combining retrieval-augmented generation with autonomous agents for knowledge tasks",                             "Free",     "#",                                                       ["rag", "retrieval"]),
      r("ag-16", "AI Agent Use Cases: Enterprise Guide",    "50 documented production use cases with ROI data from enterprise deployments",                                    "Free",     "#",                                                       ["enterprise", "use-cases"]),
      r("ag-17", "Agent Cost Optimisation",                 "Reducing LLM API spend 60-80% without sacrificing agent performance",                                            "Freemium", "#",                                                       ["cost", "optimisation"]),
      r("ag-18", "Autonomous SEO Agent Playbook",           "Building agents that conduct keyword research, audit pages, and draft briefs",                                    "Freemium", "#",                                                       ["seo-agents", "automation"]),
      r("ag-19", "Agent Workflow Templates (Notion)",       "10 ready-to-use agent workflow templates in Notion format",                                                       "Free",     "#",                                                       ["templates", "notion"]),
      r("ag-20", "Agentic AI for Content Agencies",         "Automating research, brief creation, drafting, and review workflows for agencies",                               "Freemium", "#",                                                       ["agency", "content"]),
      r("ag-21", "Production Agent Deployment Checklist",   "50-point checklist before shipping an AI agent to production",                                                    "Free",     "#",                                                       ["checklist", "production"]),
      r("ag-22", "Vercel AI SDK Agents Guide",              "Building ToolLoopAgents with AI SDK 6 — full reference with examples",                                           "Free",     "https://sdk.vercel.ai",                                  ["vercel", "ai-sdk", "agents"]),
      r("ag-23", "Fine-tuning vs Prompting vs RAG",         "Decision framework for when to fine-tune, when to prompt-engineer, and when to use RAG",                         "Free",     "#",                                                       ["fine-tuning", "rag", "decision"]),
      r("ag-24", "Agentic AI Starter Kit (GitHub)",         "Open-source starter kit with agents, tools, memory, and evals pre-configured",                                   "Free",     "#",                                                       ["open-source", "starter"]),
      r("ag-25", "Agent Prompt Library (250+)",             "Curated collection of tested agent system prompts across 12 use cases",                                          "Freemium", "#",                                                       ["prompts", "library"]),
      r("ag-26", "Multi-Modal Agent Guide",                 "Incorporating vision, audio, and document understanding into agent pipelines",                                    "Free",     "#",                                                       ["multimodal", "vision"]),
      r("ag-27", "Agent Scaling Patterns",                  "Horizontal agent scaling, task queues, and parallel execution strategies",                                        "Paid",     "#",                                                       ["scaling", "production"]),
      r("ag-28", "Crew AI vs Autogen Comparison 2026",      "Updated head-to-head comparison with benchmarks on 8 task categories",                                           "Free",     "#",                                                       ["crewai", "autogen", "comparison"]),
      r("ag-29", "Real-Time Agent Streaming UX Guide",      "Designing streaming UIs for agent output with Next.js and AI SDK",                                               "Free",     "#",                                                       ["streaming", "ux", "nextjs"]),
      r("ag-30", "Agent Integration Hub",                   "Integrating AI agents with Slack, Notion, Linear, GitHub, and 20+ external services",                           "Freemium", "#",                                                       ["integrations", "slack", "notion"]),
      r("ag-31", "Enterprise Agent Governance Guide",       "Policies, audit trails, and access control frameworks for enterprise agent deployments",                          "Paid",     "#",                                                       ["governance", "enterprise"]),
    ],
  },
  {
    slug: "mcp",
    name: "MCP & Tooling",
    description: "MCP server directory, configuration references, security checklists, and tooling for the Model Context Protocol ecosystem.",
    icon: "Wrench",
    accent: "text-amber-400",
    resources: [
      r("mcp-1",  "MCP Official Documentation",            "Complete Model Context Protocol specification from Anthropic",                                                    "Free",     "https://modelcontextprotocol.io",                         ["mcp", "spec", "anthropic"]),
      r("mcp-2",  "MCP Server Directory (Curated)",        "400+ production-ready MCP servers categorised by use case",                                                      "Free",     "#",                                                       ["directory", "servers"]),
      r("mcp-3",  "MCP Config Reference Guide",             "Full schema reference for mcp.json configurations with examples",                                                "Free",     "#",                                                       ["config", "reference"]),
      r("mcp-4",  "MCP Security Checklist",                 "20-point security audit for MCP server deployments",                                                             "Free",     "#",                                                       ["security", "audit"]),
      r("mcp-5",  "Building Your First MCP Server",         "Step-by-step tutorial: build, test, and publish an MCP server in TypeScript",                                    "Free",     "#",                                                       ["tutorial", "typescript"]),
      r("mcp-6",  "MCP for Claude Desktop: Complete Setup", "Configure 10+ MCP servers in Claude Desktop with security best practices",                                       "Free",     "#",                                                       ["claude-desktop", "setup"]),
      r("mcp-7",  "MCP vs Function Calling vs Plugins",     "When to use MCP vs native function calling vs legacy ChatGPT plugins",                                           "Free",     "#",                                                       ["comparison", "function-calling"]),
      r("mcp-8",  "Supabase MCP Server Guide",              "Using the official Supabase MCP for AI-assisted database queries",                                               "Free",     "#",                                                       ["supabase", "database"]),
      r("mcp-9",  "Stripe MCP Integration",                 "Connecting Claude to Stripe for AI-assisted payment flows",                                                      "Free",     "#",                                                       ["stripe", "payments"]),
      r("mcp-10", "GitHub MCP Server Setup",                "AI-assisted code review and PR management with the GitHub MCP server",                                           "Free",     "#",                                                       ["github", "code-review"]),
      r("mcp-11", "MCP Rate Limiting & Auth Patterns",      "Implementing authentication and rate limiting in production MCP servers",                                         "Free",     "#",                                                       ["auth", "rate-limiting"]),
      r("mcp-12", "Multi-MCP Orchestration",                "Managing multiple MCP servers in a single Claude session",                                                       "Free",     "#",                                                       ["orchestration", "multi-server"]),
      r("mcp-13", "MCP Skill Templates",                    "5 production-ready MCP server templates for common use cases",                                                   "Freemium", "#",                                                       ["templates", "skills"]),
      r("mcp-14", "MCP Testing & Debugging Guide",          "Unit testing MCP tools and debugging common connection issues",                                                   "Free",     "#",                                                       ["testing", "debugging"]),
      r("mcp-15", "MCP + Vercel Edge Functions",            "Deploying MCP servers on Vercel Edge for sub-100ms response times",                                              "Free",     "#",                                                       ["vercel", "edge"]),
      r("mcp-16", "Open Source MCP Server List",            "Curated GitHub repo list of high-quality open source MCP servers",                                               "Free",     "#",                                                       ["open-source", "github"]),
      r("mcp-17", "MCP Proxy & Gateway Patterns",           "Building MCP gateway servers that proxy and orchestrate multiple backends",                                       "Freemium", "#",                                                       ["proxy", "gateway"]),
      r("mcp-18", "Enterprise MCP Deployment Guide",        "Governance, access control, and audit logging for enterprise MCP deployments",                                   "Paid",     "#",                                                       ["enterprise", "governance"]),
    ],
  },
  {
    slug: "developer-tools",
    name: "Developer Tools",
    description: "LLM API guides, prompt engineering handbooks, AI SDK integration docs, and developer tooling for AI-powered applications.",
    icon: "Code2",
    accent: "text-green-400",
    resources: [
      r("dev-1",  "Vercel AI SDK 6 Documentation",          "Official docs for the Vercel AI SDK — streaming, tools, agents, structured output",                              "Free",     "https://sdk.vercel.ai",                                  ["vercel", "ai-sdk", "nextjs"]),
      r("dev-2",  "LLM API Provider Comparison 2026",       "Side-by-side comparison of OpenAI, Anthropic, Google, Groq, and 10+ others",                                    "Free",     "#",                                                       ["comparison", "apis"]),
      r("dev-3",  "Prompt Engineering Handbook",             "Systematic techniques for reliable, consistent LLM outputs",                                                    "Free",     "#",                                                       ["prompts", "engineering"]),
      r("dev-4",  "AI Gateway Setup Guide",                  "Using Vercel AI Gateway to access 20+ providers with unified keys and observability",                           "Free",     "#",                                                       ["gateway", "vercel"]),
      r("dev-5",  "Streaming UI Patterns with Next.js",     "Building responsive streaming UIs with React Suspense and Server Components",                                    "Free",     "#",                                                       ["streaming", "nextjs", "react"]),
      r("dev-6",  "RAG System Architecture",                 "Production-grade retrieval-augmented generation with pgvector and Supabase",                                    "Free",     "#",                                                       ["rag", "vector", "supabase"]),
      r("dev-7",  "LLM Cost Calculator Methodology",        "How to accurately project LLM API costs for production workloads",                                               "Free",     "#",                                                       ["cost", "tokens"]),
      r("dev-8",  "Type-Safe AI Apps with TypeScript",      "Using Zod, Drizzle, and TypeScript for end-to-end type safety in AI apps",                                      "Free",     "#",                                                       ["typescript", "zod", "drizzle"]),
      r("dev-9",  "OpenAI Structured Outputs Guide",        "Using JSON mode, function calling, and structured outputs reliably",                                             "Free",     "https://platform.openai.com/docs/guides/structured-outputs", ["openai", "json", "structured"]),
      r("dev-10", "Supabase + Next.js Auth Starter",        "Complete authentication and database setup with Supabase Auth and Next.js 15",                                   "Free",     "#",                                                       ["supabase", "auth", "nextjs"]),
      r("dev-11", "Edge Functions for AI Apps",             "When and how to use Vercel/Cloudflare Edge for AI workloads",                                                    "Free",     "#",                                                       ["edge", "serverless"]),
      r("dev-12", "LLM Caching Strategies",                 "Semantic caching with Redis/Upstash to cut LLM costs 40-70%",                                                   "Free",     "#",                                                       ["caching", "redis", "cost"]),
      r("dev-13", "AI App Security Checklist",              "Input sanitisation, output validation, prompt injection defence, and rate limiting",                              "Free",     "#",                                                       ["security", "checklist"]),
      r("dev-14", "Vector Database Comparison",             "pgvector vs Pinecone vs Weaviate vs Chroma — 2026 benchmarks",                                                   "Free",     "#",                                                       ["vector", "database", "comparison"]),
      r("dev-15", "LLM Observability with Langfuse",        "Open-source tracing, cost tracking, and evaluation for production LLM apps",                                    "Free",     "#",                                                       ["observability", "langfuse"]),
      r("dev-16", "Fine-tuning OpenAI Models Guide",        "When fine-tuning beats prompting, and how to do it cost-effectively",                                            "Free",     "#",                                                       ["fine-tuning", "openai"]),
      r("dev-17", "AI SDK Migration: v4 → v6",              "Step-by-step migration guide with code examples for every breaking change",                                      "Free",     "#",                                                       ["migration", "ai-sdk"]),
      r("dev-18", "Background Job Processing for AI",       "Queuing long-running LLM tasks with Vercel, Inngest, or BullMQ",                                                "Free",     "#",                                                       ["queues", "background-jobs"]),
      r("dev-19", "AI Testing Strategies",                  "Unit, integration, and evaluation testing for LLM-powered features",                                             "Free",     "#",                                                       ["testing", "evals"]),
      r("dev-20", "Next.js 16 AI Starter Template",         "Production-ready Next.js 16 + Supabase + AI SDK boilerplate",                                                   "Free",     "#",                                                       ["template", "nextjs", "starter"]),
      r("dev-21", "Anthropic Claude API Cookbook",          "Official recipes for common Claude use cases with TypeScript examples",                                           "Free",     "https://github.com/anthropics/anthropic-cookbook",       ["anthropic", "claude", "recipes"]),
      r("dev-22", "Multi-Modal Development Guide",          "Adding image understanding, document parsing, and audio to AI apps",                                             "Free",     "#",                                                       ["multimodal", "vision"]),
      r("dev-23", "AI App Deployment Checklist",            "Pre-deployment checklist covering security, cost, latency, and observability",                                   "Free",     "#",                                                       ["deployment", "checklist"]),
      r("dev-24", "AI Rate Limiting Patterns",              "Request-level and user-level rate limiting for AI API endpoints",                                                 "Free",     "#",                                                       ["rate-limiting", "api"]),
      r("dev-25", "Production AI App Architecture",         "Reference architecture for scalable, observable, cost-efficient AI applications",                                 "Freemium", "#",                                                       ["architecture", "reference"]),
      r("dev-26", "Real-World AI App Case Studies",         "10 documented production AI apps with architecture decisions explained",                                          "Free",     "#",                                                       ["case-studies", "production"]),
      r("dev-27", "AI SDK Provider Adapter Guide",          "Building custom model provider adapters for the Vercel AI SDK",                                                  "Freemium", "#",                                                       ["adapters", "providers"]),
    ],
  },
  {
    slug: "content-seo",
    name: "Content & SEO",
    description: "AI content humanization, niche selection frameworks, content pipeline templates, and SEO strategies for the AI era.",
    icon: "Layers",
    accent: "text-primary",
    resources: [
      r("con-1",  "AI Content Humanization Complete Guide", "Techniques to consistently pass AI detection while keeping content high quality",                                 "Free",     "#",                                                       ["humanization", "ai-detection"]),
      r("con-2",  "Niche Selection Framework 2026",         "Data-driven methodology for identifying profitable, low-competition niches",                                      "Free",     "#",                                                       ["niche", "research"]),
      r("con-3",  "Content Pipeline Automation Guide",      "Building automated research → brief → draft → review pipelines with AI",                                         "Free",     "#",                                                       ["automation", "pipeline"]),
      r("con-4",  "EEAT Signals for AI-Generated Content",  "Building the experience, expertise, authority, and trustworthiness signals Google needs",                        "Free",     "#",                                                       ["eeat", "google", "quality"]),
      r("con-5",  "Content Brief Template (AI-Optimised)",  "Structured brief template that produces GEO-optimised first drafts consistently",                                "Free",     "#",                                                       ["template", "brief"]),
      r("con-6",  "Long-Form Content Strategy for GEO",     "Writing 2,000–10,000 word articles that dominate AI search citations",                                           "Free",     "#",                                                       ["long-form", "strategy"]),
      r("con-7",  "Topical Authority Building Roadmap",     "12-week roadmap to build recognised subject matter expertise in any niche",                                       "Freemium", "#",                                                       ["topical-authority", "roadmap"]),
      r("con-8",  "Internal Linking for AI Visibility",     "Internal link architecture that signals content relationships to LLMs",                                           "Free",     "#",                                                       ["internal-links", "architecture"]),
      r("con-9",  "AI Writing Tools Comparison 2026",       "Honest comparison of ChatGPT, Claude, Gemini, and specialised writers",                                          "Free",     "#",                                                       ["tools", "comparison"]),
      r("con-10", "Content Refresh Playbook",               "Identifying and updating underperforming content for AI citation recovery",                                       "Free",     "#",                                                       ["refresh", "updates"]),
      r("con-11", "Affiliate Content That Converts",        "Writing product reviews and comparisons that rank in AI search and convert",                                      "Free",     "#",                                                       ["affiliate", "conversion"]),
      r("con-12", "Newsletter Content Strategy",            "Building an email audience from AI-powered content — proven frameworks",                                          "Free",     "#",                                                       ["newsletter", "email"]),
      r("con-13", "Repurposing AI Content Across Channels", "YouTube → blog → newsletter → Twitter framework with AI automation",                                             "Free",     "#",                                                       ["repurposing", "multi-channel"]),
      r("con-14", "B2B Content for AI Discovery",           "Whitepapers, case studies, and technical content that AI sources heavily cite",                                   "Free",     "#",                                                       ["b2b", "whitepapers"]),
      r("con-15", "AI Detection Bypass Techniques",         "Linguistic and structural techniques that reduce AI content scores below 10%",                                    "Free",     "#",                                                       ["ai-detection", "bypass"]),
      r("con-16", "Content ROI Calculator",                 "Spreadsheet for calculating the ROI of your AI content investment",                                               "Free",     "#",                                                       ["roi", "spreadsheet"]),
      r("con-17", "Schema for Content Pages",               "Complete schema implementation guide for articles, how-tos, and FAQs",                                            "Free",     "#",                                                       ["schema", "structured-data"]),
      r("con-18", "Programmatic Content at Scale",          "Building 1,000+ AI-written pages that rank — without a Google penalty",                                          "Freemium", "#",                                                       ["programmatic", "scale"]),
      r("con-19", "Podcast Content SEO Guide",              "Transcription, show notes, and AI citation optimisation for podcasts",                                            "Free",     "#",                                                       ["podcast", "transcription"]),
      r("con-20", "Video SEO for AI Search",                "YouTube description and metadata strategy that feeds AI search citations",                                         "Free",     "#",                                                       ["youtube", "video"]),
      r("con-21", "Agency Content Delivery Templates",      "Client-ready Notion + Google Docs templates for content agency deliverables",                                     "Paid",     "#",                                                       ["agency", "templates"]),
      r("con-22", "Content Calendar for GEO",               "12-month editorial calendar template built around GEO citation opportunities",                                    "Free",     "#",                                                       ["calendar", "planning"]),
    ],
  },
  {
    slug: "courses",
    name: "Courses & Tutorials",
    description: "Self-paced and cohort-based courses covering GEO, agentic AI, content, development, and agency operations.",
    icon: "GraduationCap",
    accent: "text-sky-400",
    resources: [
      r("crs-1",  "GEO Optimisation Crash Course",          "4-hour self-paced video course: from GEO fundamentals to your first citation",                                   "Free",     "#",                                                       ["geo", "beginner"]),
      r("crs-2",  "Agentic AI for Beginners",               "From zero to first deployed agent: 6-hour beginner-friendly course",                                             "Free",     "#",                                                       ["agents", "beginner"]),
      r("crs-3",  "AI SDK Deep Dive",                       "3-hour hands-on tutorial: streaming, tools, agents, and structured output with AI SDK 6",                        "Free",     "#",                                                       ["ai-sdk", "coding"]),
      r("crs-4",  "MCP from Zero to Production",            "Build, secure, and deploy an MCP server in one afternoon",                                                       "Free",     "#",                                                       ["mcp", "hands-on"]),
      r("crs-5",  "Content Monetisation Masterclass",       "8-hour course: niche selection → affiliate → email → scale",                                                     "Paid",     "#",                                                       ["monetisation", "affiliate"]),
      r("crs-6",  "Agency AI Workflow Masterclass",         "How to run client AI pipelines at scale — used by 600+ agencies",                                                 "Paid",     "#",                                                       ["agency", "workflows"]),
      r("crs-7",  "Next.js 16 AI App Bootcamp",             "Build a full production AI app with Next.js 16, Supabase, and AI SDK — 10 hours",                                "Freemium", "#",                                                       ["nextjs", "bootcamp"]),
      r("crs-8",  "Prompt Engineering Certification",       "Industry-recognised 6-module certification from basics to advanced techniques",                                   "Paid",     "#",                                                       ["prompts", "certification"]),
      r("crs-9",  "SEO for the AI Era",                     "Complete course adapting traditional SEO knowledge for AI-first search",                                          "Free",     "#",                                                       ["seo", "ai-era"]),
      r("crs-10", "Build a RAG System from Scratch",        "5-hour hands-on tutorial: pgvector, embeddings, chunking, and retrieval",                                        "Free",     "#",                                                       ["rag", "vector", "hands-on"]),
      r("crs-11", "LLM Fine-tuning Practitioner Course",    "When, why, and how to fine-tune GPT-4o and Mistral models — including cost analysis",                            "Paid",     "#",                                                       ["fine-tuning", "advanced"]),
      r("crs-12", "AI for Digital Marketing Agencies",      "AI tool stack, automation, and client reporting for modern digital agencies",                                     "Freemium", "#",                                                       ["agency", "marketing"]),
      r("crs-13", "Technical SEO with AI",                  "Automating crawl analysis, schema generation, and reporting with AI",                                            "Freemium", "#",                                                       ["technical-seo", "automation"]),
      r("crs-14", "Autonomous Agent Architecture",          "Advanced course: multi-agent systems, memory, tool orchestration, and evals",                                     "Paid",     "#",                                                       ["advanced", "architecture"]),
      r("crs-15", "Build and Sell AI SaaS",                 "Full product-to-revenue course for building and monetising AI micro-SaaS",                                       "Paid",     "#",                                                       ["saas", "product", "revenue"]),
    ],
  },
  {
    slug: "videos",
    name: "Videos & Webinars",
    description: "Recorded webinars, live Q&As, YouTube deep-dives, and expert panels on AI, GEO, and the future of search.",
    icon: "Video",
    accent: "text-amber-400",
    resources: [
      r("vid-1",  "AAIO Weekly Live (YouTube)",             "Weekly live Q&A and tool demo stream — Thursdays at 7pm UTC",                                                    "Free",     "#",                                                       ["live", "youtube"]),
      r("vid-2",  "GEO Score Deep Dive Webinar",            "Recorded webinar: understanding your GEO score and interpreting platform signals",                               "Free",     "#",                                                       ["geo-score", "webinar"]),
      r("vid-3",  "AI Overview Optimisation Panel",         "Expert panel: 5 SEOs share what's working for AI Overview inclusion in 2026",                                    "Free",     "#",                                                       ["ai-overviews", "panel"]),
      r("vid-4",  "Building Agents with AI SDK Live",       "90-minute livestream build: a content research agent from scratch",                                               "Free",     "#",                                                       ["agents", "build"]),
      r("vid-5",  "State of GEO 2026 Keynote",              "Annual keynote from AAIOINC CEO on where AI search is headed",                                                   "Free",     "#",                                                       ["keynote", "geo"]),
      r("vid-6",  "MCP Config Builder Walkthrough",         "30-minute video walkthrough of building an MCP config for 8 tools",                                              "Free",     "#",                                                       ["mcp", "walkthrough"]),
      r("vid-7",  "Niche Research in 20 Minutes",           "Live walkthrough: using AI tools to validate a niche in under 20 minutes",                                       "Free",     "#",                                                       ["niche", "research"]),
      r("vid-8",  "Content Humanizer Demo",                 "Before/after demo of humanizing 3,000 words of AI-generated content",                                            "Free",     "#",                                                       ["humanizer", "demo"]),
      r("vid-9",  "GEO vs SEO: Full Breakdown",             "2-hour masterclass comparing traditional SEO and GEO strategies",                                                "Free",     "#",                                                       ["geo", "seo", "comparison"]),
      r("vid-10", "Enterprise AI Panel",                    "Roundtable with 4 enterprise AI leads on production deployment challenges",                                       "Free",     "#",                                                       ["enterprise", "panel"]),
      r("vid-11", "Stripe Integration for AI Apps",         "Full walkthrough: Stripe Checkout, webhooks, and subscription management",                                       "Free",     "#",                                                       ["stripe", "payments"]),
      r("vid-12", "RAG System Build Livestream",            "4-hour livestream: building a production RAG system with Supabase pgvector",                                     "Free",     "#",                                                       ["rag", "supabase"]),
      r("vid-13", "Prompt Injection Attack Demos",          "Live demonstrations of 8 prompt injection attack vectors and defences",                                           "Free",     "#",                                                       ["security", "prompt-injection"]),
      r("vid-14", "AI Content Agency Setup (Full Day)",     "Full-day recorded workshop: setting up and running an AI content agency",                                         "Paid",     "#",                                                       ["agency", "workshop"]),
      r("vid-15", "Local SEO + GEO Combined Strategy",      "Webinar: integrating local SEO signals with GEO optimisation",                                                   "Free",     "#",                                                       ["local-seo", "geo"]),
      r("vid-16", "NextJS 16 + Supabase Crash Course",      "45-minute crash course: Next.js 16 App Router with Supabase Auth and Database",                                  "Free",     "#",                                                       ["nextjs", "supabase"]),
      r("vid-17", "AI Tool Demo Day (Monthly)",             "Monthly live showcase of new AI tools curated by the AAIOINC team",                                              "Free",     "#",                                                       ["tools", "demo"]),
      r("vid-18", "OpenClaw Architecture Deep Dive",        "Technical deep dive into the OpenClaw agent auditing framework",                                                  "Free",     "#",                                                       ["openclaw", "architecture"]),
      r("vid-19", "Building with Claude Sonnet",            "End-to-end demo: building a production content tool with Claude Sonnet 3.7",                                      "Free",     "#",                                                       ["claude", "anthropic"]),
    ],
  },
  {
    slug: "research",
    name: "Research & Reports",
    description: "Annual benchmarks, quarterly cost indices, survey reports, and academic research on AI search, agents, and LLMs.",
    icon: "Newspaper",
    accent: "text-green-400",
    resources: [
      r("res-1",  "State of GEO 2026 Report",               "Annual benchmark report: AI citation rates, platform breakdowns, and industry data across 5,000 websites",       "Free",     "#",                                                       ["benchmark", "annual"]),
      r("res-2",  "LLM Cost Index Q1 2026",                  "Quarterly pricing analysis across 20+ providers with trend data",                                               "Free",     "#",                                                       ["cost", "pricing", "quarterly"]),
      r("res-3",  "Agentic AI Enterprise Adoption Survey",   "Results from surveying 500 enterprise teams on AI agent deployments",                                            "Free",     "#",                                                       ["enterprise", "survey"]),
      r("res-4",  "AI Search Citation Patterns Study",       "Academic study: which content types get cited most by major LLMs (n=50,000)",                                   "Free",     "#",                                                       ["citations", "academic"]),
      r("res-5",  "GEO ROI Benchmarks 2026",                 "Data from 300 websites: median traffic lift from GEO optimisation over 12 months",                              "Free",     "#",                                                       ["roi", "benchmarks"]),
      r("res-6",  "LLM Accuracy Benchmarks",                 "Independent accuracy benchmarks across GPT, Claude, Gemini, and Mistral",                                       "Free",     "#",                                                       ["accuracy", "benchmarks"]),
      r("res-7",  "AI Content Detection False Positive Rate","Study of false positive rates across 8 AI detection tools on human-written content",                             "Free",     "#",                                                       ["ai-detection", "study"]),
      r("res-8",  "MCP Adoption in Enterprise 2026",         "Survey of 200 enterprise teams on MCP adoption, use cases, and security concerns",                              "Free",     "#",                                                       ["mcp", "enterprise"]),
      r("res-9",  "Prompt Injection Vulnerability Report",   "Security research: 60% of production AI apps are vulnerable to prompt injection",                               "Free",     "#",                                                       ["security", "research"]),
      r("res-10", "AI Token Economics Study",                "Research on LLM token usage patterns, waste, and optimisation opportunities",                                    "Free",     "#",                                                       ["tokens", "cost"]),
      r("res-11", "Developer Productivity with AI",          "Study of 2,000 developers: AI tool impact on productivity, code quality, and satisfaction",                      "Free",     "#",                                                       ["productivity", "developers"]),
    ],
  },
  {
    slug: "templates-prompts",
    name: "Templates & Prompts",
    description: "Prompt packs, content templates, agent workflow starters, and client-ready deliverable formats.",
    icon: "BookOpen",
    accent: "text-primary",
    resources: [
      r("tpl-1",  "SEO Prompt Pack (75+)",                   "75 tested prompts covering keyword research, content briefs, meta copy, schema, and more",                      "Free",     "/prompts",                                               ["prompts", "seo"]),
      r("tpl-2",  "GEO Optimisation Prompt Library",         "40+ prompts specifically for GEO — citation improvement, FAQ generation, entity markup",                        "Free",     "/prompts",                                               ["prompts", "geo"]),
      r("tpl-3",  "Agent Workflow Templates (Notion)",       "10 pre-built agent workflow templates for common business use cases",                                            "Freemium", "#",                                                       ["templates", "notion", "agents"]),
      r("tpl-4",  "Content Agency Report Templates",         "Client-ready monthly SEO, GEO, and content performance report templates",                                       "Paid",     "#",                                                       ["agency", "reporting"]),
      r("tpl-5",  "Content Brief Template (Pro)",            "Advanced brief template with GEO signals, competitor analysis, and AI guidance",                                "Paid",     "#",                                                       ["brief", "template"]),
      r("tpl-6",  "MCP Server Template (TypeScript)",        "Production-ready MCP server template with auth, logging, and error handling",                                   "Free",     "#",                                                       ["mcp", "typescript", "template"]),
      r("tpl-7",  "AI App Starter Boilerplate",              "Next.js 16 + Supabase + Stripe + AI SDK production boilerplate",                                                "Free",     "#",                                                       ["nextjs", "boilerplate", "starter"]),
      r("tpl-8",  "GEO Audit Deliverable Template",          "Client-ready Notion/PDF GEO audit template with scoring and recommendations",                                   "Freemium", "#",                                                       ["audit", "client", "template"]),
      r("tpl-9",  "Outreach Email Prompt Pack",              "30 cold outreach and link building prompt templates",                                                            "Free",     "/prompts",                                               ["outreach", "email", "prompts"]),
      r("tpl-10", "Social Media Content Prompt Pack",        "50 prompts for LinkedIn, Twitter, and YouTube content from blog posts",                                         "Free",     "/prompts",                                               ["social", "content", "prompts"]),
      r("tpl-11", "Proposal Template for GEO Services",      "Fully editable proposal template for pitching GEO services to clients",                                         "Paid",     "#",                                                       ["proposal", "agency"]),
      r("tpl-12", "AI Research Agent Starter",               "Pre-configured research agent with web search, citation, and export tools",                                     "Freemium", "#",                                                       ["agents", "research"]),
      r("tpl-13", "Affiliate Review Template",               "SEO-optimised product review template with affiliate conversion best practices",                                 "Free",     "#",                                                       ["affiliate", "review"]),
      r("tpl-14", "Technical Documentation Prompt Pack",     "20 prompts for writing clear, accurate API and developer documentation",                                        "Free",     "/prompts",                                               ["documentation", "technical"]),
      r("tpl-15", "AI Summary & Analysis Prompt Pack",       "25 prompts for summarising research papers, reports, and long documents",                                       "Free",     "/prompts",                                               ["summarisation", "research"]),
      r("tpl-16", "AI Humanization Workflow Template",       "Step-by-step Notion workflow for humanizing AI content at scale",                                               "Freemium", "#",                                                       ["humanization", "workflow"]),
      r("tpl-17", "SaaS Landing Page Copy Template",         "Conversion-focused landing page copy template with GEO-optimised structure",                                    "Free",     "#",                                                       ["saas", "landing-page", "copy"]),
      r("tpl-18", "Weekly Content Calendar Template",        "Google Sheets editorial calendar with GEO citation tracking built in",                                          "Free",     "#",                                                       ["calendar", "tracking"]),
      r("tpl-19", "Niche Research Report Template",          "Client-ready niche analysis report template with profitability scoring",                                         "Freemium", "#",                                                       ["niche", "report"]),
      r("tpl-20", "AI Product Manager Prompt Pack",          "35 prompts for product discovery, spec writing, user stories, and roadmap planning",                            "Free",     "/prompts",                                               ["product", "prompts"]),
      r("tpl-21", "Agent System Prompt Templates (Pro)",     "50 battle-tested system prompts for production AI agents across 8 use cases",                                   "Paid",     "/prompts",                                               ["agents", "system-prompts"]),
      r("tpl-22", "SEO Tool Stack Comparison Template",      "Spreadsheet for comparing and evaluating SEO tool subscriptions by ROI",                                        "Free",     "#",                                                       ["tools", "comparison"]),
      r("tpl-23", "Automated Reporting Dashboard Template",  "Google Looker Studio template for AI/SEO automated client reporting",                                           "Freemium", "#",                                                       ["reporting", "dashboard"]),
      r("tpl-24", "Developer Onboarding Prompt Pack",        "15 prompts for code review, documentation, PR descriptions, and team onboarding",                               "Free",     "/prompts",                                               ["developer", "onboarding"]),
      r("tpl-25", "Press Release & PR Prompt Pack",         "20 prompts for writing AI-assisted press releases, media pitches, and announcements",                            "Free",     "/prompts",                                               ["pr", "press-release"]),
      r("tpl-26", "Data Analysis Prompt Pack",              "30 prompts for analysing CSV data, survey results, and business metrics with AI",                                "Free",     "/prompts",                                               ["data", "analysis"]),
      r("tpl-27", "Full-Stack AI App Checklist",            "Pre-launch checklist for security, performance, cost, and observability",                                        "Free",     "#",                                                       ["checklist", "launch"]),
      r("tpl-28", "LLM Evaluation Scorecard Template",      "Spreadsheet for systematically evaluating LLM outputs against golden test sets",                                 "Free",     "#",                                                       ["evaluation", "evals"]),
      r("tpl-29", "Competitor Analysis Prompt Pack",        "25 prompts for researching competitors, analysing positioning, and finding gaps",                                 "Free",     "/prompts",                                               ["competitive", "analysis"]),
      r("tpl-30", "YouTube Script Prompt Pack",             "40 prompts for scripting, hook writing, CTA optimisation, and chapter timestamps",                               "Free",     "/prompts",                                               ["youtube", "video", "scripts"]),
      r("tpl-31", "Content Audit Spreadsheet Template",     "Full content audit template with GEO score, traffic, and improvement priority columns",                          "Freemium", "#",                                                       ["audit", "content"]),
      r("tpl-32", "Interview & Research Prompt Pack",       "20 prompts for preparing interview questions, synthesising transcripts, and writing summaries",                   "Free",     "/prompts",                                               ["research", "interviews"]),
      r("tpl-33", "Customer Support Prompt Pack",           "30 prompts for writing help docs, support replies, and escalation scripts",                                       "Free",     "/prompts",                                               ["support", "customer"]),
      r("tpl-34", "SEO Link Building Prompt Pack",          "25 prompts for prospecting, outreach personalisation, and link building strategy",                               "Free",     "/prompts",                                               ["link-building", "outreach"]),
      r("tpl-35", "Notion AI Workspace Template",           "Complete Notion workspace with AI prompts, brief templates, and publishing checklists",                           "Freemium", "#",                                                       ["notion", "workspace"]),
      r("tpl-36", "Product Hunt Launch Prompt Pack",        "15 prompts for writing Product Hunt taglines, comments, and launch copy",                                        "Free",     "/prompts",                                               ["product-hunt", "launch"]),
      r("tpl-37", "AI Ad Copy Prompt Pack",                 "35 prompts for Facebook, Google, and LinkedIn ads — including A/B testing variants",                              "Free",     "/prompts",                                               ["ads", "copy"]),
      r("tpl-38", "Agency SOW Template (AI Services)",      "Statement of Work template for AI consulting and managed services engagements",                                   "Paid",     "#",                                                       ["agency", "sow"]),
    ],
  },
]

// Derived helpers
export const RESOURCE_CATEGORY_SLUGS = RESOURCE_CATEGORIES.map((c) => c.slug)

export function getCategoryBySlug(slug: string): ResourceCategory | undefined {
  return RESOURCE_CATEGORIES.find((c) => c.slug === slug)
}

export const totalResourceCount = RESOURCE_CATEGORIES.reduce(
  (sum, c) => sum + c.resources.length, 0
)
